### ISSUE TITLE
Virus total flagging Rust-Code-Raid-Bot.exe

### ISSUE THREAD

**Issue by scotjam** [NapoII/Rust-Code-Raid-Bot#1]
https://www.virustotal.com/gui/file/ed5f47f16e95948d2d3d61941bca6bb43474f1ab9b10c16c35ed2e1efd6bdfda/detection

Might be a false positive but good to be aware

DeepInstinct: MALICIOUS

**Comment by NapoII** [comment]
This is normal for py to exe. If you are suspicious, just use the pyhton code where you can see every line of code.
