### ISSUE TITLE
logNow not found and problem with the win32 api

### ISSUE THREAD

**Issue by Daxi90** [NapoII/Rust-Code-Raid-Bot#2]
Hi there is a problem with missing logNow dependencie and the win32 api

**Comment by NapoII** [comment]
give me some  min

**Comment by NapoII** [comment]
It's fun to occasionally look back at my old code and see how my programming skills started. Wow, that was definitely spaghetti code! xD

But hey, it still did what it had to do!

**Comment by NapoII** [comment]
fix

**Comment by NapoII** [comment]
fix

**Comment by Daxi90** [comment]
Awesome, thanks for fixing.
I think thats an awesome project for starting :)

**Comment by Daxi90** [comment]
Unfortunately, it no longer seems to work, 
the key combination is only recognized intermittently and I can't understand exactly what the trigger is.

In addition, the messages in the chat are blocked because entries are made too quickly

**Comment by Daxi90** [comment]
Its running ;)
Only have to set the sleep time up to 4 seconds in chat messages ;)

**Comment by NapoII** [comment]
if you code raid one base pls let me know !!
